# Generated by Django 5.1.4 on 2024-12-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='supplierimages')),
                ('supplier_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('supplier_type', models.CharField(choices=[('ST', 'Stockist'), ('MF', 'Manufacturer'), ('DS', 'Distributor')], default='ST', max_length=2)),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
